cmake_minimum_required(VERSION 2.8.7)


include(ExternalProject)
if(CMAKE_EXTRA_GENERATOR)
  set(gen "${CMAKE_EXTRA_GENERATOR} - ${CMAKE_GENERATOR}")
else()
  set(gen "${CMAKE_GENERATOR}")
endif()



set(proj QWT)
ExternalProject_Add(${proj}
  SVN_REPOSITORY http://svn.code.sf.net/p/qwt/code/branches/qwt-6.0/
  SOURCE_DIR ${proj}
  BINARY_DIR ${proj}
  SVN_REVISION -r 1599
  DEPENDS ""
  CMAKE_GENERATOR ${gen}
  CONFIGURE_COMMAND ${QT_QMAKE_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/${proj}
  INSTALL_COMMAND ""
)



set(proj dti_tract_stat)
ExternalProject_Add(${proj}
  DOWNLOAD_COMMAND ""
  INSTALL_COMMAND ""
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}
  BINARY_DIR ${proj}-build
  DEPENDS QWT
  CMAKE_GENERATOR ${gen}
  CMAKE_ARGS
    -DVTK_DIR:PATH=${VTK_DIR}
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DQWT_LIB_PATH:FILEPATH=${CMAKE_CURRENT_BINARY_DIR}/QWT/lib
    -DQWT_INCLUDE_DIR_GIVEN:PATH=${CMAKE_CURRENT_BINARY_DIR}/QWT/src
    -DCOMPILE_EXTERNAL_DTIPROCESS:BOOL=OFF
    -DCOMPILE_MERGERSTATWITHFIBER:BOOL=ON
    -DCOMPILE_FIBERCOMPARE:BOOL=ON
    -DCOMPILE_DTITRACTSTAT:BOOL=ON
    -DCOMPILE_DTIATLASFIBERANALYZER:BOOL=ON
    -DVTK_DIR:PATH=${VTK_DIR}
    -DITK_DIR:PATH=${ITK_DIR}
    -DSlicerExecutionModel_DIR:PATH=${SlicerExecutionModel_DIR}
    -DOPT_USE_SYSTEM_VTK:BOOL=ON
    -DOPT_USE_SYSTEM_ITK:BOOL=ON
    -DOPT_USE_SYSTEM_SlicerExecutionModel:BOOL=ON
    -DQT_QMAKE_EXECUTABLE:FILEPATH=${QT_QMAKE_EXECUTABLE}
    -DMIDAS_PACKAGE_EMAIL:STRING=${MIDAS_PACKAGE_EMAIL}
    -DMIDAS_PACKAGE_API_KEY:STRING=${MIDAS_PACKAGE_API_KEY}
    -DADDITIONAL_C_FLAGS:STRING=${ADDITIONAL_C_FLAGS}
    -DADDITIONAL_CXX_FLAGS:STRING=${ADDITIONAL_CXX_FLAGS}
    -DEXTENSION_NAME:STRING=${EXTENSION_NAME}
    -DEXTENSION_SUPERBUILD_BINARY_DIR:PATH=${${EXTENSION_NAME}_BINARY_DIR}
    -DDTIAtlasFiberAnalyzer_BUILD_SLICER_EXTENSION:BOOL=OFF
    # Slicer
    -DSlicer_DIR:PATH=${Slicer_DIR}
    -DSlicerExecutionModel_DEFAULT_CLI_RUNTIME_OUTPUT_DIRECTORY:PATH=${SlicerExecutionModel_DEFAULT_CLI_RUNTIME_OUTPUT_DIRECTORY}
    -DSlicerExecutionModel_DEFAULT_CLI_INSTALL_RUNTIME_DESTINATION:PATH=${SlicerExecutionModel_DEFAULT_CLI_INSTALL_RUNTIME_DESTINATION}
    -DSlicerExecutionModel_DEFAULT_CLI_INSTALL_LIBRARY_DESTINATION:PATH=${SlicerExecutionModel_DEFAULT_CLI_INSTALL_LIBRARY_DESTINATION}
)


