FIND_PACKAGE(Boost)

IF(Boost_FOUND)
  SET(USE_BOOST_LIB true)
ENDIF(Boost_FOUND)

INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIR})

LINK_DIRECTORIES(${Boost_LIBRARY_DIRS})

IF(NOT WIN32 OR CYGWIN)
  SET(BOOST_LIBRARIES boost_program_options)
ENDIF(NOT WIN32 OR CYGWIN)

